name:  print hello world
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello
        run: echo "Hello world"
      - name: Repo clone
        uses: actions/checkout@v4
      - name: function
        run : node haha.js